### ISSUE TITLE
Closing livebox on client side.

### ISSUE THREAD

**Issue by jnryu87** [jazzfog/LiveBox#1]
Hey Pavel,
First of all, thank you for creating this amazing library.
I am trying to use livebox instead of popup on client side for oauth login process.
So I have js library which will create livebox and render oauth login page with URL on client side.
When user is logged in, I need to close the livebox.
I  couldn't use hide() as I am not able to pass handler object when open a link on livebox.
So now I am closing it like,
$('.liveboxCloseBtn').click() on my side and it seems to work !
but I am wondering if there's any better way to handle it.
Or if I am using wrong, please let me know how to use livebox better.
Merry Christmas !

**Comment by jazzfog** [comment]
Hey jnryu!
How do you create the livebox window?
If programmatically (as opposed to using livebox class name) and you can access window's handler then you can use method `.hide()` as described here https://liveboxjs.com/documentation/controlling
Merry Christmas!

**Comment by jnryu87** [comment]
Thank you for quick reply !
And I just feel so sorry for bothering your Christmas holidays...
the livebox will be created like below on client side.

$.livebox({ title: 'oauth2 login',
type: 'ajax', content: oauth_url, (this url includes querystring.) height:
900, customClass: { liveboxOverlay: 'myOverlayClass' } });

I don't create livebox with handler(var handler = $.livebox). Because I
thought just rendering a page on livebox will be OK...
But I got a problem when I wanted to close it on my side(oauth server side).

When user clicks login button, I send ajax POST request to server. And on
success, I want to close current livebox.
My first approach was, $('.livebox').hide(). But it didn't work... :*(
I will try and play again with the livebox and if I have any better
solution, I will also let you know.
Thank you again for replying on Sunday(Holiday) and have a lovely day,
Sincerely,
jn


2018년 12월 23일 (일) 오후 9:02, Pavel <notifications@github.com>님이 작성:

**Comment by jazzfog** [comment]
That's right! You are very close. 

In fact you have two options. The problem with `.hide()` is that the library allows you to open multiple windows one on top of another and so it need to know exactly what window you want to close. Or you can close all.

1) In order to close all - you can do `$.fn.livebox.hideAll()`

2) If you build multiple window UI you can close one particular window you need to close. All you need to do is to take advantage of the object `$.livebox` returns.

```
var handler = $.livebox({
  title: 'Hello',
  type: 'text',
  content: 'World!'
});

// Instead of timeout use event of your choice
setTimeout(function() {
  console.log('Closing...')
  handler.hide();
}, 2000)
```

Have fun!
